basepath = ".."
locales = [
    "fr",
]
includes = [
    { path = "_configs/toolkit.toml" },
    { path = "_configs/devtools-client.toml" },
]

[env]
l = "{l10n_base}/{locale}/"

[[paths]]
reference = "browser/**"
l10n = "{l}browser/**"

[[paths]]
reference = "browser/branding/official/**"
l10n = "{l}browser/branding/official/**"

[[paths]]
reference = "browser/branding/enterprise/**"
l10n = "{l}browser/branding/enterprise/**"

[[paths]]
reference = "browser/extensions/formautofill/**"
l10n = "{l}browser/extensions/formautofill/**"

[[paths]]
reference = "browser/extensions/report-site-issue/**"
l10n = "{l}browser/extensions/report-site-issue/**"

[[paths]]
reference = "devtools/startup/**"
l10n = "{l}devtools/startup/**"
